apiVersion: apps/v1
kind: Deployment
metadata:
  name: hephaestus-gui-frontend
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hephaestus-gui
  template:
    metadata:
      labels:
        app: hephaestus-gui
    spec:
      containers:
      - name: hephaestus-gui
        image: hephaestus-gui-frontend:0.11
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hephaestus-gui-frontend
  namespace: monitoring
spec:
  selector:
    app: hephaestus-gui
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80

